name: Push Docker image to GHCR

on:
  workflow_dispatch: # 可以手动触发
  # 或者 push/cron 等触发方式
  # push:
  #   branches:
  #     - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Pull Docker image from Docker Hub
        run: |
          docker pull baserow/baserow:2.0.6

      - name: Tag image for GHCR
        run: |
          docker tag baserow/baserow:2.0.6 ghcr.io/${{ github.actor }}/baserow:2.0.6

      - name: Push image to GHCR
        run: |
          docker push ghcr.io/${{ github.actor }}/baserow:2.0.6
